#!/bin/zsh

assert() {
       if [[ "$2" != "$3" ]]; then
       	   echo "Failure: $1\n\tExpected: $3\n\tReceived: $2"
	   ERR=1
       fi
}

DIR=$(mktemp -d)
trap "rm -rf $DIR" EXIT
cd "$DIR"

echo "testing: "$(pwd)
echo 'test' > test


[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"


